####################################################################################################################################################
# SOLAR_SYSTEM_TARGETS
# A complete list of Solar System targets excluding small bodies (but including Pluto).
# (target_name, alt_names, target_type, primary, lid)
####################################################################################################################################################

SOLAR_SYSTEM_TARGETS = [
  ("Sun"           , ["NAIF ID 10"               ], "Star"      , "N/A"    , "urn:nasa:pds:context:target:star.sun"                                 ),
  ("Mercury"       , ["NAIF ID 199"              ], "Planet"   , "Sun"    , "urn:nasa:pds:context:target:planet.mercury"                           ),
  ("Venus"         , ["NAIF ID 299"              ], "Planet"   , "Sun"    , "urn:nasa:pds:context:target:planet.venus"                             ),


  ("Earth"         , ["NAIF ID 399"              ], "Planet"   , "Sun"    , "urn:nasa:pds:context:target:planet.earth"                             ),
  ("Moon"          , ["Earth I (Moon)",
                      "NAIF ID 301"              ], "Satellite", "Earth"  , "urn:nasa:pds:context:target:satellite.earth.moon"                     ),


  ("Mars"          , ["NAIF ID 499"              ], "Planet"   , "Sun"    , "urn:nasa:pds:context:target:planet.mars"                              ),
  ("Mars Rings"    , [                           ], "Ring"     , "Mars"   , "urn:nasa:pds:context:target:ring.mars.rings"                          ),
  ("Phobos"        , ["Mars I (Phobos)",
                      "NAIF ID 401"              ], "Satellite", "Mars"   , "urn:nasa:pds:context:target:satellite.mars.phobos"                    ),
  ("Deimos"        , ["Mars II (Deimos)",
                      "NAIF ID 402"              ], "Satellite", "Mars"   , "urn:nasa:pds:context:target:satellite.mars.deimos"                    ),


  ("Jupiter"       , ["NAIF ID 599"              ], "Planet"   , "Sun"    , "urn:nasa:pds:context:target:planet.jupiter"                           ),
  ("Jupiter Rings" , [                           ], "Ring"     , "Jupiter", "urn:nasa:pds:context:target:ring.jupiter.rings"                       ),
  ("Io"            , ["Jupiter I (Io)",
                      "NAIF ID 501"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.io"                     ),
  ("Europa"        , ["Jupiter II (Europa)",
                      "NAIF ID 502"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.europa"                 ),
  ("Ganymede"      , ["Jupiter III (Ganymede)",
                      "NAIF ID 503"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.ganymede"               ),
  ("Callisto"      , ["Jupiter IV (Callisto)",
                      "NAIF ID 504"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.callisto"               ),
  ("Amalthea"      , ["Jupiter V (Amalthea)",
                      "NAIF ID 505"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.amalthea"               ),
  ("Himalia"       , ["Jupiter VI (Himalia)",
                      "NAIF ID 506"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.himalia"                ),
  ("Elara"         , ["Jupiter VII (Elara)",
                      "NAIF ID 507"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.elara"                  ),
  ("Pasiphae"      , ["Jupiter VIII (Pasiphae)",
                      "NAIF ID 508"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.pasiphae"               ),
  ("Sinope"        , ["Jupiter IX (Sinope)",
                      "NAIF ID 509"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.sinope"                 ),
  ("Lysithea"      , ["Jupiter X (Lysithea)",
                      "NAIF ID 510"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.lysithea"               ),
  ("Carme"         , ["Jupiter XI (Carme)",
                      "NAIF ID 511"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.carme"                  ),
  ("Ananke"        , ["Jupiter XII (Ananke)",
                      "NAIF ID 512"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.ananke"                 ),
  ("Leda"          , ["Jupiter XIII (Leda)",
                      "NAIF ID 513"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.leda"                   ),
  ("Thebe"         , ["Jupiter XIV (Thebe)",
                      "NAIF ID 514"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.thebe"                  ),
  ("Adrastea"      , ["Jupiter XV (Adrastea)",
                      "NAIF ID 515"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.adrastea"               ),
  ("Metis"         , ["Jupiter XVI (Metis)",
                      "NAIF ID 516"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.metis"                  ),
  ("Callirrhoe"    , ["Jupiter XVII (Callirrhoe)",
                      "S/1999 J 1",
                      "NAIF ID 517"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.callirrhoe"             ),
  ("Themisto"      , ["Jupiter XVIII (Themisto)",
                      "S/1975 J 1",
                      "S/2000 J 1",
                      "NAIF ID 518"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.themisto"               ),
  ("Magaclite"     , ["Jupiter XIX (Magaclite)",
                      "NAIF ID 519"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.magaclite"              ),
  ("Taygete"       , ["Jupiter XX (Taygete)",
                      "S/2000 J 9",
                      "NAIF ID 520"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.taygete"                ),
  ("Chaldene"      , ["Jupiter XXI (Chaldene)",
                      "S/2000 J 10",
                      "NAIF ID 521"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.chaldene"               ),
  ("Harpalyke"     , ["Jupiter XXII (Harpalyke)",
                      "S/2000 J 5",
                      "NAIF ID 522"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.harpalyke"              ),
  ("Kalyke"        , ["Jupiter XXIII (Kalyke)",
                      "S/2000 J 2",
                      "NAIF ID 523"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.kalyke"                 ),
  ("Iocaste"       , ["Jupiter XXIV (Iocaste)",
                      "S/2000 J 3",
                      "NAIF ID 524"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.iocaste"                ),
  ("Erinome"       , ["Jupiter XXV (Erinome)",
                      "S/2000 J 4",
                      "NAIF ID 525"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.erinome"                ),
  ("Isonoe"        , ["Jupiter XXVI (Isonoe)",
                      "S/2002 J 1",
                      "NAIF ID 526"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.isonoe"                 ),
  ("Praxidike"     , ["Jupiter XXVII (Praxidike)",
                      "S/2000 J 7",
                      "NAIF ID 527"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.praxidike"              ),
  ("Autonoe"       , ["Jupiter XXVIII (Autonoe)",
                      "S/2001 J 1",
                      "NAIF ID 528"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.autonoe"                ),
  ("Thyone"        , ["Jupiter XXIX (Thyone)",
                      "S/2001 J 2",
                      "NAIF ID 529"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.thyone"                 ),
  ("Hermippe"      , ["Jupiter XXX (Hermippe)",
                      "S/2001 J 3",
                      "NAIF ID 530"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.hermippe"               ),
  ("Aitne"         , ["Jupiter XXXI (Aitne)",
                      "S/2001 J 11",
                      "NAIF ID 531"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.aitne"                  ),
  ("Eurydome"      , ["Jupiter XXXII (Eurydome)",
                      "S/2001 J 4",
                      "NAIF ID 532"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.eurydome"               ),
  ("Euanthe"       , ["Jupiter XXXIII (Euanthe)",
                      "S/2001 J 7",
                      "NAIF ID 533"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.euanthe"                ),
  ("Euporie"       , ["Jupiter XXXIV (Euporie)",
                      "S/2001 J 10",
                      "NAIF ID 534"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.euporie"                ),
  ("Orthosie"      , ["Jupiter XXXV (Orthosie)",
                      "S/2001 J 9",
                      "NAIF ID 535"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.orthosie"               ),
  ("Sponde"        , ["Jupiter XXXVI (Sponde)",
                      "S/2001 J 5",
                      "NAIF ID 536"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.sponde"                 ),
  ("Kale"          , ["Jupiter XXXVII (Kale)",
                      "S/2001 J 8",
                      "NAIF ID 537"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.kale"                   ),
  ("Pasithee"      , ["Jupiter XXXVIII (Pasithee)",
                      "S/2001 J 6",
                      "NAIF ID 538"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.pasithee"               ),
  ("Hegemone"      , ["Jupiter XXXIX (Hegemone)",
                      "S/2003 J 8",
                      "NAIF ID 539"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.hegemone"               ),
  ("Mneme"         , ["Jupiter XL (Mneme)",
                      "S/2003 J 21",
                      "NAIF ID 540"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.mneme"                  ),
  ("Aoede"         , ["Jupiter XLI (Aoede)",
                      "S/2003 J 7",
                      "NAIF ID 541"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.aoede"                  ),
  ("Thelxinoe"     , ["Jupiter XLII (Thelxinoe)",
                      "S/2003 J 22",
                      "NAIF ID 542"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.thelxinoe"              ),
  ("Arche"         , ["Jupiter XLIII (Arche)",
                      "S/2002 J 1",
                      "NAIF ID 543"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.arche"                  ),
  ("Kallichore"    , ["Jupiter XLIV (Kallichore)",
                      "S/2003 J 11",
                      "NAIF ID 544"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.kallichore"             ),
  ("Helike"        , ["Jupiter XLV (Helike)",
                      "S/2003 J 6",
                      "NAIF ID 545"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.helike"                 ),
  ("Carpo"         , ["Jupiter XLVI (Carpo)",
                      "S/2003 J 20",
                      "NAIF ID 546"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.carpo"                  ),
  ("Eukelade"      , ["Jupiter XLVII (Eukelade)",
                      "S/2003 J 1",
                      "NAIF ID 547"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.eukelade"               ),
  ("Cyllene"       , ["Jupiter XLVIII (Cyllene)",
                      "S/2003 J 13",
                      "NAIF ID 548"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.cyllene"                ),
  ("Kore"          , ["Jupiter XLIX (Kore)",
                      "S/2003 J 14",
                      "NAIF ID 549"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.kore"                   ),
  ("S/2003 J 17"   , ["Jupiter L",
                      "NAIF ID 550"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j17"               ),
  ("S/2010 J 1"    , ["Jupiter LI",
                      "NAIF ID 551"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2010j1"                ),
  ("S/2010 J 2"    , ["Jupiter LII",
                      "NAIF ID 552"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2010j2"                ),
  ("Dia"           , ["Jupiter LIII (Dia)",
                      "S/2000 J 11",
                      "NAIF ID 553"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.dia"                    ),
  ("S/2016 J 1"    , ["Jupiter LIV",
                      "NAIF ID 554"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2016j1"                ),
  ("S/2003 J 18"   , ["Jupiter LV",
                      "NAIF ID 555"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j18"               ),
  ("S/2011 J 2"    , ["Jupiter LVI",
                      "NAIF ID 556"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2011j2"                ),
  ("S/2003 J 5"    , ["Jupiter LVII",
                      "NAIF ID 557"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j5"                ),
  ("S/2003 J 15"   , ["Jupiter LVIII",
                      "NAIF ID 558"              ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j15"               ),
  ("S/2003 J 2"    , ["NAIF ID 55060"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j2"                ),
  ("S/2003 J 3"    , ["NAIF ID 55061"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j3"                ),
  ("S/2003 J 4"    , ["NAIF ID 55062"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j4"                ),
  ("S/2003 J 9"    , ["NAIF ID 55064"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j9"                ),
  ("S/2003 J 10"   , ["NAIF ID 55065"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j10"               ),
  ("S/2003 J 12"   , ["NAIF ID 55066"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j12"               ),
  ("S/2003 J 16"   , ["NAIF ID 55068"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j16"               ),
  ("S/2003 J 19"   , ["NAIF ID 55070"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j19"               ),
  ("S/2003 J 23"   , ["NAIF ID 55071"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2003j23"               ),
  ("S/2011 J 1"    , ["NAIF ID 55074"            ], "Satellite", "Jupiter", "urn:nasa:pds:context:target:satellite.jupiter.s2011j1"                ),


  ("Saturn"        , ["NAIF ID 699"              ], "Planet"   , "Sun"   , "urn:nasa:pds:context:target:planet.saturn"                             ),
  ("Saturn Rings"  , [                           ], "Ring"     , "Saturn", "urn:nasa:pds:context:target:ring.saturn.rings"                         ),
  ("Mimas"         , ["Saturn I (Mimas)",
                      "NAIF ID 601"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.mimas"                    ),
  ("Enceladus"     , ["Saturn II (Enceladus)",
                      "NAIF ID 602"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.enceladus"                ),
  ("Tethys"        , ["Saturn III (Tethys)",
                      "NAIF ID 603"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.tethys"                   ),
  ("Dione"         , ["Saturn IV (Dione)",
                      "NAIF ID 604"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.dione"                    ),
  ("Rhea"          , ["Saturn V (Rhea)",
                      "NAIF ID 605"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.rhea"                     ),
  ("Titan"         , ["Saturn VI (Titan)",
                      "NAIF ID 606"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.titan"                    ),
  ("Hyperion"      , ["Saturn VII (Hyperion)",
                      "NAIF ID 607"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.hyperion"                 ),
  ("Iapetus"       , ["Saturn VIII (Iapetus)",
                      "NAIF ID 608"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.iapetus"                  ),
  ("Phoebe"        , ["Saturn IX (Phoebe)",
                      "NAIF ID 609"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.phoebe"                   ),
  ("Janus"         , ["Saturn X (Janus)",
                      "NAIF ID 610"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.janus"                    ),
  ("Epimetheus"    , ["Saturn XI (Epimetheus)",
                      "NAIF ID 611"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.epimetheus"               ),
  ("Helene"        , ["Saturn XII (Helene)",
                      "S/1980 S 6",
                      "NAIF ID 612"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.helene"                   ),
  ("Telesto"       , ["Saturn XIII (Telesto)",
                      "S/1980 S 13",
                      "NAIF ID 613"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.telesto"                  ),
  ("Calypso"       , ["Saturn XIV (Calypso)",
                      "S/1980 S 25",
                      "NAIF ID 614"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.calypso"                  ),
  ("Atlas"         , ["Saturn XV (Atlas)",
                      "S/1980 S 28",
                      "NAIF ID 615"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.atlas"                    ),
  ("Prometheus"    , ["Saturn XVI (Prometheus)",
                      "S/1980 S 27",
                      "NAIF ID 616"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.prometheus"               ),
  ("Pandora"       , ["Saturn XVII (Pandora)",
                      "S/1980 S 26",
                      "NAIF ID 617"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.pandora"                  ),
  ("Pan"           , ["Saturn XVIII (Pan)",
                      "S/1981 S 13",
                      "NAIF ID 618"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.pan"                      ),
  ("Ymir"          , ["Saturn XIX (Ymir)",
                      "S/2000 S 1",
                      "NAIF ID 619"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.ymir"                     ),
  ("Paaliaq"       , ["Saturn XX (Paaliaq)",
                      "S/2000 S 2",
                      "NAIF ID 620"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.paaliaq"                  ),
  ("Tarvos"        , ["Saturn XXI (Tarvos)",
                      "S/2000 S 4",
                      "NAIF ID 621"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.tarvos"                   ),
  ("Ijiraq"        , ["Saturn XXII (Ijiraq)",
                      "S/2000 S 6",
                      "NAIF ID 622"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.ijiraq"                   ),
  ("Suttungr"      , ["Saturn XXIII (Suttungr)",
                      "S/2000 S 12",
                      "NAIF ID 623"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.suttungr"                 ),
  ("Kiviuq"        , ["Saturn XXIV (Kiviuq)",
                      "S/2000 S 5",
                      "NAIF ID 624"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.kiviuq"                   ),
  ("Mundilfari"    , ["Saturn XXV (Mundilfari)",
                      "S/2000 S 9",
                      "NAIF ID 625"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.mundilfari"               ),
  ("Albiorix"      , ["Saturn XXVI (Albiorix)",
                      "S/2000 S 11",
                      "NAIF ID 626"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.albiorix"                 ),
  ("Skathi"        , ["Saturn XXVII (Skathi)",
                      "S/2000 S 8",
                      "NAIF ID 627"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.skathi"                   ),
  ("Erriapus"      , ["Saturn XXVIII (Erriapus)",
                      "S/2000 S 10",
                      "NAIF ID 628"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.erriapus"                 ),
  ("Siarnaq"       , ["Saturn XXIX (Siarnaq)",
                      "S/2000 S 3",
                      "NAIF ID 629"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.siarnaq"                  ),
  ("Thrymr"        , ["Saturn XXX (Thrymr)",
                      "S/2000 S 7",
                      "NAIF ID 630"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.thrymr"                   ),
  ("Narvi"         , ["Saturn XXXI (Narvi)",
                      "S/2003 S 1",
                      "NAIF ID 631"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.narvi"                    ),
  ("Methone"       , ["Saturn XXXII (Methone)",
                      "S/2004 S 1",
                      "NAIF ID 632"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.methone"                  ),
  ("Pallene"       , ["Saturn XXXIII (Pallene)",
                      "S/2004 S 2",
                      "NAIF ID 633"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.pallene"                  ),
  ("Polydeuces"    , ["Saturn XXXIV (Polydeuces)",
                      "S/2004 S 5",
                      "NAIF ID 634"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.polydeuces"               ),
  ("Daphnis"       , ["Saturn XXXV (Daphnis)",
                      "S/2005 S 1",
                      "NAIF ID 635"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.daphnis"                  ),
  ("Aegir"         , ["Saturn XXXVI (Aegir)",
                      "S/2004 S 10",
                      "NAIF ID 636"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.aegir"                    ),
  ("Bebhionn"      , ["Saturn XXXVII (Bebhionn)",
                      "S/2004 S 11",
                      "NAIF ID 637"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.bebhionn"                 ),
  ("Bergelmir"     , ["Saturn XXXVIII (Bergelmir)",
                      "S/2004 S 15",
                      "NAIF ID 638"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.bergelmir"                ),
  ("Bestla"        , ["Saturn XXXIX (Bestla)",
                      "S/2004 S 18",
                      "NAIF ID 639"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.bestla"                   ),
  ("Farbauti"      , ["Saturn XL (Farbauti)",
                      "S/2004 S 9",
                      "NAIF ID 640"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.farbauti"                 ),
  ("Fenrir"        , ["Saturn XLI (Fenrir)",
                      "S/2004 S 16",
                      "NAIF ID 641"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.fenrir"                   ),
  ("Fornjot"       , ["Saturn XLII (Fornjot)",
                      "S/2004 S 8",
                      "NAIF ID 642"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.fornjot"                  ),
  ("Hati"          , ["Saturn XLIII (Hati)",
                      "S/2004 S 14",
                      "NAIF ID 643"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.hati"                     ),
  ("Hyrrokkin"     , ["Saturn XLIV (Hyrrokkin)",
                      "NAIF ID 644"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.hyrrokkin"                 ),
  ("Kari"          , ["Saturn XLV (Kari)",
                      "S/2006 S 2",
                      "NAIF ID 645"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.kari"                     ),
  ("Loge"          , ["Saturn XLVI (Loge)",
                      "S/2006 S 5",
                      "NAIF ID 646"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.loge"                     ),
  ("Skoll"         , ["Saturn XLVII (Skoll)",
                      "S/2006 S 8",
                      "NAIF ID 647"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.skoll"                    ),
  ("Surtur"        , ["Saturn XLVIII (Surtur)",
                      "S/2006 S 7",
                      "NAIF ID 648"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.surtur"                   ),
  ("Anthe"         , ["Saturn XLIX (Anthe)",
                      "S/2007 S 4",
                      "NAIF ID 649"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.anthe"                    ),
  ("Jarnsaxa"      , ["Saturn L (Jarnsaxa)",
                      "S/2006 S 6",
                      "NAIF ID 650"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.jarnsaxa"                 ),
  ("Greip"         , ["Saturn LI (Greip)",
                      "S/2006 S 4",
                      "NAIF ID 651"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.greip"                    ),
  ("Tarqeq"        , ["Saturn LII (Tarqeq)",
                      "S/2007 S 1",
                      "NAIF ID 652"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.tarqeq"                   ),
  ("Aegaeon"       , ["Saturn LIII (Aegaeon)",
                      "S/2008 S 1",
                      "NAIF ID 653"              ], "Satellite", "Saturn", "urn:nasa:pds:context:target:satellite.saturn.aegaeon"                  ),
  ("S/2004 S 7"    , ["NAIF ID 65035"            ], "Satellite", "Saturn" , "urn:nasa:pds:context:target:satellite.saturn.s2004s7"                 ),
  ("S/2004 S 12"   , ["NAIF ID 65040"            ], "Satellite", "Saturn" , "urn:nasa:pds:context:target:satellite.saturn.s2004s12"                ),
  ("S/2004 S 13"   , ["NAIF ID 65041"            ], "Satellite", "Saturn" , "urn:nasa:pds:context:target:satellite.saturn.s2004s13"                ),
  ("S/2004 S 17"   , ["NAIF ID 65045"            ], "Satellite", "Saturn" , "urn:nasa:pds:context:target:satellite.saturn.s2004s17"                ),
  ("S/2006 S 1"    , ["NAIF ID 65048"            ], "Satellite", "Saturn" , "urn:nasa:pds:context:target:satellite.saturn.s2006s1"                 ),
  ("S/2006 S 3"    , ["NAIF ID 65050"            ], "Satellite", "Saturn" , "urn:nasa:pds:context:target:satellite.saturn.s2006s3"                 ),
  ("S/2007 S 2"    , ["NAIF ID 65055"            ], "Satellite", "Saturn" , "urn:nasa:pds:context:target:satellite.saturn.s2007s2"                 ),
  ("S/2007 S 3"    , ["NAIF ID 65056"            ], "Satellite", "Saturn" , "urn:nasa:pds:context:target:satellite.saturn.s2007s3"                 ),


  ("Uranus"        , ["NAIF ID 799"              ], "Planet"   , "Sun"   , "urn:nasa:pds:context:target:planet.uranus"                             ),
  ("Uranus Rings"  , [                           ], "Ring"     , "Uranus", "urn:nasa:pds:context:target:ring.uranus.rings"                         ),
  ("Ariel"         , ["Uranus I (Ariel)",
                      "NAIF ID 701"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.ariel"                    ),
  ("Umbriel"       , ["Uranus II (Umbriel)",
                      "NAIF ID 702"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.umbriel"                  ),
  ("Titania"       , ["Uranus III (Titania)",
                      "NAIF ID 703"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.titania"                  ),
  ("Oberon"        , ["Uranus IV (Oberon)",
                      "NAIF ID 704"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.oberon"                   ),
  ("Miranda"       , ["Uranus V (Miranda)",
                      "NAIF ID 705"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.miranda"                  ),
  ("Cordelia"      , ["Uranus VI (Cordelia)",
                      "S/1986 U 7",
                      "NAIF ID 706"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.cordelia"                 ),
  ("Ophelia"       , ["Uranus VII (Ophelia)",
                      "S/1986 U 8",
                      "NAIF ID 707"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.ophelia"                  ),
  ("Bianca"        , ["Uranus VIII (Bianca)",
                      "S/1986 U 9",
                      "NAIF ID 708"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.bianca"                   ),
  ("Cressida"      , ["Uranus IX (Cressida)",
                      "S/1986 U 3",
                      "NAIF ID 709"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.cressida"                 ),
  ("Desdemona"     , ["Uranus X (Desdemona)",
                      "S/1986 U 6",
                      "NAIF ID 710"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.desdemona"                ),
  ("Juliet"        , ["Uranus XI (Juliet)",
                      "S/1986 U 2",
                      "NAIF ID 711"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.juliet"                   ),
  ("Portia"        , ["Uranus XII (Portia)",
                      "S/1986 U 1",
                      "NAIF ID 712"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.portia"                   ),
  ("Rosalind"      , ["Uranus XIII (Rosalind)",
                      "S/1986 U 4",
                      "NAIF ID 713"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.rosalind"                 ),
  ("Belinda"       , ["Uranus XIV (Belinda)",
                      "S/1986 U 5",
                      "NAIF ID 714"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.belinda"                  ),
  ("Puck"          , ["Uranus XV (Puck)",
                      "S/1985 U 1",
                      "NAIF ID 715"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.puck"                     ),
  ("Caliban"       , ["Uranus XVI (Caliban)",
                      "S/1997 U 1",
                      "NAIF ID 716"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.caliban"                  ),
  ("Sycorax"       , ["Uranus XVII (Sycorax)",
                      "S/1997 U 2",
                      "NAIF ID 717"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.sycorax"                  ),
  ("Prospero"      , ["Uranus XVIII (Prospero)",
                      "S/1999 U 3",
                      "NAIF ID 718"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.prospero"                 ),
  ("Setebos"       , ["Uranus XIX (Setebos)",
                      "S/1999 U 1",
                      "NAIF ID 719"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.setebos"                  ),
  ("Stephano"      , ["Uranus XX (Stephano)",
                      "S/1999 U 2",
                      "NAIF ID 720"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.stephano"                 ),
  ("Trinculo"      , ["Uranus XXI (Trinculo)",
                      "S/2001 U 1",
                      "NAIF ID 721"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.trinculo"                 ),
  ("Francisco"     , ["Uranus XXII (Francisco)",
                      "S/2001 U 3",
                      "NAIF ID 722"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.francisco"                ),
  ("Margaret"      , ["Uranus XXIII (Margaret)",
                      "S/2003 U 3",
                      "NAIF ID 723"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.margaret"                 ),
  ("Ferdinand"     , ["Uranus XXIV (Ferdinand)",
                      "NAIF ID 724"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.ferdinand"                ),
  ("Perdita"       , ["Uranus XXV (Perdita)",
                      "S/1986 U 10",
                      "NAIF ID 725"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.perdita"                  ),
  ("Mab"           , ["Uranus XXVI (Mab)",
                      "S/2003 U 1",
                      "NAIF ID 726"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.mab"                      ),
  ("Cupid"         , ["Uranus XXVII (Cupid)",
                      "S/2003 U 2",
                      "NAIF ID 727"              ], "Satellite", "Uranus", "urn:nasa:pds:context:target:satellite.uranus.cupid"                    ),


  ("Neptune"       , ["NAIF ID 899"              ], "Planet"   , "Sun"    , "urn:nasa:pds:context:target:planet.neptune"                           ),
  ("Neptune Rings" , [                           ], "Ring"     , "Neptune", "urn:nasa:pds:context:target:ring.neptune.rings"                       ),
  ("Triton"        , ["Neptune I (Triton)",
                      "NAIF ID 801"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.triton"                 ),
  ("Nereid"        , ["Neptune II (Nereid)",
                      "NAIF ID 802"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.nereid"                 ),
  ("Naiad"         , ["Neptune III (Naiad)",
                      "NAIF ID 803"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.naiad"                  ),
  ("Thalassa"      , ["Neptune IV (Thalassa)",
                      "NAIF ID 804"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.thalassa"               ),
  ("Despina"       , ["Neptune V (Despina)",
                      "NAIF ID 805"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.despina"                ),
  ("Galatea"       , ["Neptune VI (Galatea)",
                      "NAIF ID 806"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.galatea"                ),
  ("Larissa"       , ["Neptune VII (Larissa)",
                      "NAIF ID 807"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.larissa"                ),
  ("Proteus"       , ["Neptune VIII (Proteus)",
                      "NAIF ID 808"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.proteus"                ),
  ("Halimede"      , ["Neptune IX (Halimede)",
                      "S/2002 N 1",
                      "NAIF ID 809"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.halimede"               ),
  ("Psamathe"      , ["Neptune X (Psamathe)",
                      "S/2003 N 1",
                      "NAIF ID 810"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.psamathe"               ),
  ("Sao"           , ["Neptune XI (Sao)",
                      "S/2002 N 2",
                      "NAIF ID 811"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.sao"                    ),
  ("Laomedeia"     , ["Neptune XII (Laomedeia)",
                      "S/2002 N 3",
                      "NAIF ID 812"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.laomedeia"              ),
  ("Neso"          , ["Neptune XIII (Neso)",
                      "S/2003 N 2",
                      "NAIF ID 813"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.neso"                   ),
  ("Hippocamp"     , ["Neptune XIV (Hippocamp)",
                      "S/2004 N 1",
                      "NAIF ID 814"              ], "Satellite", "Neptune", "urn:nasa:pds:context:target:satellite.neptune.hippocamp"              ),


  ("(134340) Pluto", ["Pluto",
                      "NAIF ID 999"              ], "Dwarf Planet", "Sun"           , "urn:nasa:pds:context:target:dwarf_planet.134340_pluto"      ),
  ("Charon"        , ["(134340) Pluto I (Charon)",
                      "Pluto I (Charon)",
                      "NAIF ID 901"              ], "Satellite"   , "(134340) Pluto", "urn:nasa:pds:context:target:satellite.134340_pluto.charon"  ),
  ("Nix"           , ["(134340) Pluto II (Nix)",
                      "Pluto II (Nix)",
                      "NAIF ID 902"              ], "Satellite"   , "(134340) Pluto", "urn:nasa:pds:context:target:satellite.134340_pluto.nix"     ),
  ("Hydra"         , ["(134340) Pluto III (Hydra)",
                      "Pluto III (Hydra)",
                      "NAIF ID 903"              ], "Satellite"   , "(134340) Pluto", "urn:nasa:pds:context:target:satellite.134340_pluto.hydra"   ),
  ("Kerberos"      , ["(134340) Pluto IV (Kerberos)",
                      "Pluto IV (Kerberos)",
                      "NAIF ID 904"              ], "Satellite"   , "(134340) Pluto", "urn:nasa:pds:context:target:satellite.134340_pluto.kerberos"),
  ("Styx"          , ["(134340) Pluto V (Styx)",
                      "Pluto V (Styx)",
                      "NAIF ID 905"              ], "Satellite"   , "(134340) Pluto", "urn:nasa:pds:context:target:satellite.134340_pluto.styx"    ),
]

####################################################################################################################################################

