egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/12945xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/12946xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/12952xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13089xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13136xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13272xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13273xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13386xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13387xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13389xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13390xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13391xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13392xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13433xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13479xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13490xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13491xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13492xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13493xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13494xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13495xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13496xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13497xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13498xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13499xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13500xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13501xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13502xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13503xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13504xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13505xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13506xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13507xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13508xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13509xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13510xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13511xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13512xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13513xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13514xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13515xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13516xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13517xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13518xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13519xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13520xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13521xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13522xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13523xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13524xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13525xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13526xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13527xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13528xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13529xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13530xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13531xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13532xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13533xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13534xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13535xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13536xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13537xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13538xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13539xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13540xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13541xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13542xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13543xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13544xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13545xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13546xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13547xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13548xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13549xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13550xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13551xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13552xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13553xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13555xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13556xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13557xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13558xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13559xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13567xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13568xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13569xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13570xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13571xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13573xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13574xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13575xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13576xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13577xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13578xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13579xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13580xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13581xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13582xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13583xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13586xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13587xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13588xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13589xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13590xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13591xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13592xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13593xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13594xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13595xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13596xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13601xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13602xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13603xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13604xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13605xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13606xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13607xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13608xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13609xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13610xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13611xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13612xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13613xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13614xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13615xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13616xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13617xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13618xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13619xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13621xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13622xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13623xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13624xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13625xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13626xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13627xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13628xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13629xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13630xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13631xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13632xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13633xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13634xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13635xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13636xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13637xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13638xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13639xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13642xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13643xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13644xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13645xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13649xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13650xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13651xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13652xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13653xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13654xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13655xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13671xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13672xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13694xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13696xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13697xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13699xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13726xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13728xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13729xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13735xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13737xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13738xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13780xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13828xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13831xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13832xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13833xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13836xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13903xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13910xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13911xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13996xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13997xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/13998xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14019xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14047xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14048xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14049xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14051xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14053xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14054xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14056xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14057xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14058xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14090xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14091xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14125xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14126xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14127xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14128xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14129xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14132xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14136xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14137xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14138xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14139xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14216xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14217xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14218xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14219xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14293xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14294xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14295xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14296xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14299xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14319xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14320xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14321xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14416xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14438xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14440xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14441xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14447xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14448xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14470xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14471xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14488xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14489xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14490xxxxx/*.xml 
egrep footer /Volumes/Marks-Migration-HD/pds4/COISS_xxxx/cassini_iss_cruise/data_raw/14510xxxxx/*.xml 
