#!/bin/bash -e

### conda update conda

conda create -y --name vicar-migration pytest python=2.7
conda install -y --name vicar-migration -c anaconda typing

# conda create -y --name vicar-migration pycodestyle pytest scipy python=2.7
# conda install -y -n vicar-migration -c anaconda lxml pyparsing
# conda install -y -n vicar-migration -c conda-forge fs ply sh
# source activate vicar-migration

echo
echo "Run 'source activate vicar-migration' to activate the environment."
