find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1454\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1455\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1456\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1457\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1458\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1459\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1460\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1461\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1462\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1463\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1464\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1465\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1466\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1467\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1468\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1469\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1470\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1471\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1472\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1473\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1474\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1475\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1476\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1477\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1478\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1479\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1480\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1481\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1482\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1483\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1484\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1485\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1486\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1487\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1488\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1489\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1490\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1491\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1492\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1493\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1494\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1495\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1496\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1497\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1498\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1499\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1500\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1501\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1502\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1503\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1504\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1505\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1506\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1507\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1508\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1509\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1510\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1511\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1512\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1513\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1514\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1515\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1516\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1517\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1518\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1519\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1520\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1521\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1522\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1523\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1524\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1525\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1526\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1527\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1528\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1529\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1530\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1531\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1532\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1533\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1534\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1535\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1536\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1537\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1538\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1539\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1540\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1541\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1542\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1543\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1544\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1545\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1546\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1547\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1548\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1549\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1550\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1551\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1552\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1553\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1554\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1555\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1556\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1557\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1558\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1559\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1560\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1561\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1562\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1563\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1564\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1565\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1566\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1567\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1568\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1569\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1570\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1571\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1572\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1573\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1574\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1575\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1576\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1577\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1578\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1579\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1580\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1581\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1582\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1583\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1584\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1585\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1586\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1587\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1588\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1589\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1590\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1591\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1592\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1593\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1594\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1595\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1596\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1597\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1598\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1599\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1600\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1601\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1602\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1603\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1604\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1605\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1606\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1607\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1608\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1609\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1610\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1611\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1612\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1613\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1614\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1615\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1616\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1617\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1618\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1619\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1620\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1621\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1622\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1623\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1624\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1625\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1626\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1627\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1628\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1629\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1630\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1631\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1632\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1633\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1634\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1635\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1636\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1637\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1638\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1639\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1640\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1641\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1642\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1643\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1644\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1645\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1646\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1647\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1648\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1649\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1650\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1651\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1652\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1653\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1654\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1655\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1656\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1657\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1658\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1659\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1660\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1661\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1662\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1663\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1664\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1665\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1666\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1667\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1669\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1670\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1671\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1672\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1673\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1674\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1675\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1676\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1677\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1678\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1679\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1680\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1681\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1682\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1683\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1684\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1685\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1686\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1687\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1688\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1689\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1690\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1691\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1692\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1693\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1694\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1695\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1696\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1697\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1698\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1699\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1700\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1701\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1702\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1703\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1704\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1705\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1706\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1707\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1708\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1709\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1710\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1711\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1712\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1713\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1714\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1715\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1716\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1717\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1718\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1719\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1720\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1721\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1722\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1723\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1724\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1725\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1726\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1727\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1728\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1729\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1730\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1731\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1732\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1733\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1734\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1735\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1736\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1737\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1738\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1739\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1740\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1741\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1742\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1743\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1744\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1745\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1746\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1747\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1748\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1749\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1750\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1751\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1752\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1753\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1754\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1755\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1756\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1757\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1758\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1759\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1760\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1761\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1762\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1763\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1764\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1765\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1766\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1767\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1768\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1769\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1770\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1771\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1772\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1773\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1774\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1775\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1776\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1777\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1778\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1779\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1780\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1781\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1782\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1783\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1784\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1785\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1786\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1787\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1788\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1789\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1790\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1791\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1792\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1793\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1794\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1795\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1796\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1797\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1798\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1799\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1800\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1801\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1802\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1803\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1804\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1805\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1806\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1807\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1808\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1809\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1810\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1811\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1812\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1813\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1814\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1815\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1816\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1817\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1818\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1819\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1820\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1821\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1822\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1823\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1824\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1825\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1826\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1827\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1828\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1829\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1830\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1831\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1832\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1833\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1834\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1835\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1836\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1837\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1838\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1839\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1840\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1841\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1842\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1843\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1844\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1845\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1846\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1847\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1848\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1849\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1850\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1851\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1852\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1853\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1854\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1855\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1856\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1857\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1858\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1859\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1860\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1861\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1862\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1863\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1864\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1865\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1866\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1867\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1868\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1869\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1870\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1871\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1872\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1873\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1874\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1875\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1876\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1877\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1878\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1879\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1880\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1881\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1882\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1883\*_\*.IMG | wc
find /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/*/data/ -name \?1884\*_\*.IMG | wc
