rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2002/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2002/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2003/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2003/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2004/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2004/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2005/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2005/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2006/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2006/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2007/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2007/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2008/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2008/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2009/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2009/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2010/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2010/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2011/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2011/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2012/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2012/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2013/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2013/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2014/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2014/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2015/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2015/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2016/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2016/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2017/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2017/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2018/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2018/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2019/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2019/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2020/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2020/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2021/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2021/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2022/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2022/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2023/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2023/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2024/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2024/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2025/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2025/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2026/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2026/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2027/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2027/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2028/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2028/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2029/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2029/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2030/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2030/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2031/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2031/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2032/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2032/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2033/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2033/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2034/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2034/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2035/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2035/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2036/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2036/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2037/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2037/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2038/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2038/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2039/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2039/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2040/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2040/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2041/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2041/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2042/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2042/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2043/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2043/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2044/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2044/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2045/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2045/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2046/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2046/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2047/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2047/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2048/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2048/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2049/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2049/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2050/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2050/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2051/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2051/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2052/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2052/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2053/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2053/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2054/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2054/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2055/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2055/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2056/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2056/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2057/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2057/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2058/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2058/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2059/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2059/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2060/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2060/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2061/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2061/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2062/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2062/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2063/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2063/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2064/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2064/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2065/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2065/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2066/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2066/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2067/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2067/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2068/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2068/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2069/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2069/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2070/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2070/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2071/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2071/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2072/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2072/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2073/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2073/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2074/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2074/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2075/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2075/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2076/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2076/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2077/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2077/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2078/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2078/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2079/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2079/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2080/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2080/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2081/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2081/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2082/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2082/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2083/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2083/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2084/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2084/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2085/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2085/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2086/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2086/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2087/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2087/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2088/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2088/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2089/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2089/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2090/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2090/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2091/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2091/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2092/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2092/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2093/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2093/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2094/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2094/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2095/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2095/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2096/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2096/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2097/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2097/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2098/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2098/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2099/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2099/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2100/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2100/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2101/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2101/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2102/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2102/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2103/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2103/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2104/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2104/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2105/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2105/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2106/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2106/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2107/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2107/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2108/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2108/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2109/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2109/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2110/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2110/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2111/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2111/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2112/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2112/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2113/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2113/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2114/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2114/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2115/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2115/
rsync -av --exclude=extras --exclude=cumindex.\* /Volumes/pdsdata2/holdings/volumes/COISS_2xxx/COISS_2116/ /Volumes/Migration-4TB/pds3/COISS_2xxx/COISS_2116/
